name: foodgram
include:
  - path: ../backend/compose.yaml

services:
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram_proxy
    hostname: foodgram_proxy
    image: nginx:1.25.4-alpine
    ports:
      - "7777:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_data:/vol/static
      - media_data:/vol/media
    depends_on:
      - backend
      - frontend

volumes:
  static_data:
  media_data:
