---
name: Main Foodgram Workflow

on:
  push:
    branches:
      - main

jobs:
  build_backend:
    name: Build and Push Backend to DockerHub
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest

  build_frontend:
    name: Build and Push Frontend to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs:
      - build_backend
      - build_frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy compose.production.yaml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: compose.production.yaml
          target: foodgram
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd foodgram
            sudo docker compose -f compose.production.yaml pull
            sudo docker compose -f compose.production.yaml down
            sudo docker compose -f compose.production.yaml up -d
            sudo docker image prune -af
